### ISSUE TITLE
CLI allows to send commands in the context of non-existing terminals

### ISSUE THREAD

**Issue by blackbit42** [inmbolmie/5250_usb_converter#4]
If e.g. your terminal is at address 3, you start the program that defaults to address 0 and you issue a command different than 'setactiveterminal', the program aborts as an terminal identifier will be accessed that doesn't exist.
Also, 'setactiveterminal' should verify that the requested terminal ID is indeed existing.

**Comment by inmbolmie** [comment]
Yes, my fault because someone already reported this error but I forgot to fix it.
