### ISSUE TITLE
Instead of a shell, present a login prompt

### ISSUE THREAD

**Issue by blackbit42** [inmbolmie/5250_usb_converter#5]
Usual terminal behavior is to ask the user to authenticate themselves before getting a shell, which makes sense generally.

**Comment by inmbolmie** [comment]
Thanks, that sounds reasonable as it will provide the true vintage look and feel for the terminal. Maybe as a command line feature because I imagine for most users showing directly the prompt is ok.

**Comment by inmbolmie** [comment]
I made this, you need to pass the "-l" parameter at the command line, BUT I've found that in most modern Linuxes (like my Ubuntu) the _login_ command only can be run by root, so to make this work you have to run the script as root or make some nasty changes to your system to enable _login_ to run as non-root user.

I wouldn't recommend to anyone to run the script as root, but I will leave this option for "advanced" users.
